//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace servicioFaceWCF.facturasspp2
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://webservice.face.gob.es", ConfigurationName = "facturasspp2.FacturaSSPPWebServiceProxyPort", ProtectionLevel = System.Net.Security.ProtectionLevel.Sign)]
    public interface FacturaSSPPWebServiceProxyPort
    {

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#enviarFactura", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.EnviarFacturaResponse enviarFactura(servicioFaceWCF.facturasspp2.EnviarFacturaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#enviarFactura", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.EnviarFacturaResponse> enviarFacturaAsync(servicioFaceWCF.facturasspp2.EnviarFacturaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarFactura", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarFacturaResponse consultarFactura(string numeroRegistro);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarFactura", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarFacturaResponse> consultarFacturaAsync(string numeroRegistro);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#anularFactura", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.AnularFacturaResponse anularFactura(string numeroRegistro, string motivo);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#anularFactura", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.AnularFacturaResponse> anularFacturaAsync(string numeroRegistro, string motivo);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarEstados", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarEstadosResponse consultarEstados();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarEstados", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarEstadosResponse> consultarEstadosAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarUnidades", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarRelacionesResponse consultarUnidades();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarUnidades", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarRelacionesResponse> consultarUnidadesAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarNIFs", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarNIFsResponse consultarNIFs();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarNIFs", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarNIFsResponse> consultarNIFsAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarAdministraciones", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarAdministracionesResponse consultarAdministraciones();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarAdministraciones", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarAdministracionesResponse> consultarAdministracionesAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarAdministracionesRepositorio", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarAdministracionesRepositorioResponse consultarAdministracionesRepositorio();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarAdministracionesRepositorio", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarAdministracionesRepositorioResponse> consultarAdministracionesRepositorioAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarUnidadesPorAdministracion", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarRelacionesPorAdministracionResponse consultarUnidadesPorAdministracion(string codigoDir);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarUnidadesPorAdministracion", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarRelacionesPorAdministracionResponse> consultarUnidadesPorAdministracionAsync(string codigoDir);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarNIFsPorAdministracion", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style = System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.ConsultarNIFsPorAdministracionResponse consultarNIFsPorAdministracion(string codigoDir);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarNIFsPorAdministracion", ReplyAction = "*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarNIFsPorAdministracionResponse> consultarNIFsPorAdministracionAsync(string codigoDir);

        // CODEGEN: El parámetro 'request' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarListadoFacturas", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse consultarListadoFacturas(servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://webservice.face.gob.es#consultarListadoFacturas", ReplyAction = "*")]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse> consultarListadoFacturasAsync(servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class EnviarFacturaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string correoField;

        private FacturaFile facturaField;

        private AnexoFile[] anexosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FacturaFile factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("anexo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public AnexoFile[] anexos
        {
            get
            {
                return this.anexosField;
            }
            set
            {
                this.anexosField = value;
                this.RaisePropertyChanged("anexos");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class FacturaFile : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string facturaField;

        private string nombreField;

        private string mimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mime
        {
            get
            {
                return this.mimeField;
            }
            set
            {
                this.mimeField = value;
                this.RaisePropertyChanged("mime");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarListadoFactura : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoField;

        private string descripcionField;

        private ConsultarFactura facturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsultarFactura factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarFactura : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroRegistroField;

        private EstadoFactura tramitacionField;

        private EstadoFactura anulacionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroRegistro
        {
            get
            {
                return this.numeroRegistroField;
            }
            set
            {
                this.numeroRegistroField = value;
                this.RaisePropertyChanged("numeroRegistro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EstadoFactura tramitacion
        {
            get
            {
                return this.tramitacionField;
            }
            set
            {
                this.tramitacionField = value;
                this.RaisePropertyChanged("tramitacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EstadoFactura anulacion
        {
            get
            {
                return this.anulacionField;
            }
            set
            {
                this.anulacionField = value;
                this.RaisePropertyChanged("anulacion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class EstadoFactura : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoField;

        private string descripcionField;

        private string motivoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string motivo
        {
            get
            {
                return this.motivoField;
            }
            set
            {
                this.motivoField = value;
                this.RaisePropertyChanged("motivo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarListadoFacturaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private ConsultarListadoFactura[] facturasField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("consultarListadoFactura", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ConsultarListadoFactura[] facturas
        {
            get
            {
                return this.facturasField;
            }
            set
            {
                this.facturasField = value;
                this.RaisePropertyChanged("facturas");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class Resultado : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoField;

        private string descripcionField;

        private string codigoSeguimientoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string codigoSeguimiento
        {
            get
            {
                return this.codigoSeguimientoField;
            }
            set
            {
                this.codigoSeguimientoField = value;
                this.RaisePropertyChanged("codigoSeguimiento");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarNIFsPorAdministracionResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private OGNIFs[] nifsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("info", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public OGNIFs[] nifs
        {
            get
            {
                return this.nifsField;
            }
            set
            {
                this.nifsField = value;
                this.RaisePropertyChanged("nifs");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class OGNIFs : object, System.ComponentModel.INotifyPropertyChanged
    {

        private UnidadDir3 organoGestorField;

        private string nifField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public UnidadDir3 organoGestor
        {
            get
            {
                return this.organoGestorField;
            }
            set
            {
                this.organoGestorField = value;
                this.RaisePropertyChanged("organoGestor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nif
        {
            get
            {
                return this.nifField;
            }
            set
            {
                this.nifField = value;
                this.RaisePropertyChanged("nif");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class UnidadDir3 : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoField;

        private string nombreField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarRelacionesPorAdministracionResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private OGUTOC[] relacionesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public OGUTOC[] relaciones
        {
            get
            {
                return this.relacionesField;
            }
            set
            {
                this.relacionesField = value;
                this.RaisePropertyChanged("relaciones");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class OGUTOC : object, System.ComponentModel.INotifyPropertyChanged
    {

        private UnidadDir3 organoGestorField;

        private UnidadDir3 unidadTramitadoraField;

        private UnidadDir3 oficinaContableField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public UnidadDir3 organoGestor
        {
            get
            {
                return this.organoGestorField;
            }
            set
            {
                this.organoGestorField = value;
                this.RaisePropertyChanged("organoGestor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public UnidadDir3 unidadTramitadora
        {
            get
            {
                return this.unidadTramitadoraField;
            }
            set
            {
                this.unidadTramitadoraField = value;
                this.RaisePropertyChanged("unidadTramitadora");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public UnidadDir3 oficinaContable
        {
            get
            {
                return this.oficinaContableField;
            }
            set
            {
                this.oficinaContableField = value;
                this.RaisePropertyChanged("oficinaContable");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarAdministracionesRepositorioResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private UnidadDir3[] administracionesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public UnidadDir3[] administraciones
        {
            get
            {
                return this.administracionesField;
            }
            set
            {
                this.administracionesField = value;
                this.RaisePropertyChanged("administraciones");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarAdministracionesResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private UnidadDir3[] administracionesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("administracion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public UnidadDir3[] administraciones
        {
            get
            {
                return this.administracionesField;
            }
            set
            {
                this.administracionesField = value;
                this.RaisePropertyChanged("administraciones");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarNIFsResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private OGNIFs[] nifsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("info", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public OGNIFs[] nifs
        {
            get
            {
                return this.nifsField;
            }
            set
            {
                this.nifsField = value;
                this.RaisePropertyChanged("nifs");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarRelacionesResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private OGUTOC[] relacionesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("relacion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public OGUTOC[] relaciones
        {
            get
            {
                return this.relacionesField;
            }
            set
            {
                this.relacionesField = value;
                this.RaisePropertyChanged("relaciones");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nombreField;

        private string codigoField;

        private string descripcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarEstadosResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private Estado[] estadosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("estado", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public Estado[] estados
        {
            get
            {
                return this.estadosField;
            }
            set
            {
                this.estadosField = value;
                this.RaisePropertyChanged("estados");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class AnularFactura : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroRegistroField;

        private string mensajeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroRegistro
        {
            get
            {
                return this.numeroRegistroField;
            }
            set
            {
                this.numeroRegistroField = value;
                this.RaisePropertyChanged("numeroRegistro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class AnularFacturaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private AnularFactura facturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public AnularFactura factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class ConsultarFacturaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private ConsultarFactura facturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public ConsultarFactura factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class EnviarFactura : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string numeroRegistroField;

        private string organoGestorField;

        private string unidadTramitadoraField;

        private string oficinaContableField;

        private string identificadorEmisorField;

        private string numeroFacturaField;

        private string serieFacturaField;

        private string fechaRecepcionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroRegistro
        {
            get
            {
                return this.numeroRegistroField;
            }
            set
            {
                this.numeroRegistroField = value;
                this.RaisePropertyChanged("numeroRegistro");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string organoGestor
        {
            get
            {
                return this.organoGestorField;
            }
            set
            {
                this.organoGestorField = value;
                this.RaisePropertyChanged("organoGestor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadTramitadora
        {
            get
            {
                return this.unidadTramitadoraField;
            }
            set
            {
                this.unidadTramitadoraField = value;
                this.RaisePropertyChanged("unidadTramitadora");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oficinaContable
        {
            get
            {
                return this.oficinaContableField;
            }
            set
            {
                this.oficinaContableField = value;
                this.RaisePropertyChanged("oficinaContable");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string identificadorEmisor
        {
            get
            {
                return this.identificadorEmisorField;
            }
            set
            {
                this.identificadorEmisorField = value;
                this.RaisePropertyChanged("identificadorEmisor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string numeroFactura
        {
            get
            {
                return this.numeroFacturaField;
            }
            set
            {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public string serieFactura
        {
            get
            {
                return this.serieFacturaField;
            }
            set
            {
                this.serieFacturaField = value;
                this.RaisePropertyChanged("serieFactura");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaRecepcion
        {
            get
            {
                return this.fechaRecepcionField;
            }
            set
            {
                this.fechaRecepcionField = value;
                this.RaisePropertyChanged("fechaRecepcion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class EnviarFacturaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private Resultado resultadoField;

        private EnviarFactura facturaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Resultado resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public EnviarFactura factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
                this.RaisePropertyChanged("factura");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://webservice.face.gob.es")]
    public partial class AnexoFile : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string anexoField;

        private string nombreField;

        private string mimeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string anexo
        {
            get
            {
                return this.anexoField;
            }
            set
            {
                this.anexoField = value;
                this.RaisePropertyChanged("anexo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mime
        {
            get
            {
                return this.mimeField;
            }
            set
            {
                this.mimeField = value;
                this.RaisePropertyChanged("mime");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "consultarListadoFacturas", WrapperNamespace = "https://webservice.face.gob.es", IsWrapped = true)]
    public partial class consultarListadoFacturasRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("numeroRegistro", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public string[] request;

        public consultarListadoFacturasRequest()
        {
        }

        public consultarListadoFacturasRequest(string[] request)
        {
            this.request = request;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "consultarListadoFacturasResponse", WrapperNamespace = "https://webservice.face.gob.es", IsWrapped = true)]
    public partial class consultarListadoFacturasResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "", Order = 0)]
        public servicioFaceWCF.facturasspp2.ConsultarListadoFacturaResponse @return;

        public consultarListadoFacturasResponse()
        {
        }

        public consultarListadoFacturasResponse(servicioFaceWCF.facturasspp2.ConsultarListadoFacturaResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturaSSPPWebServiceProxyPortChannel : servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturaSSPPWebServiceProxyPortClient : System.ServiceModel.ClientBase<servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort>, servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort
    {

        public FacturaSSPPWebServiceProxyPortClient()
        {
        }

        public FacturaSSPPWebServiceProxyPortClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public FacturaSSPPWebServiceProxyPortClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public FacturaSSPPWebServiceProxyPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public FacturaSSPPWebServiceProxyPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public servicioFaceWCF.facturasspp2.EnviarFacturaResponse enviarFactura(servicioFaceWCF.facturasspp2.EnviarFacturaRequest request)
        {
            return base.Channel.enviarFactura(request);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.EnviarFacturaResponse> enviarFacturaAsync(servicioFaceWCF.facturasspp2.EnviarFacturaRequest request)
        {
            return base.Channel.enviarFacturaAsync(request);
        }

        public servicioFaceWCF.facturasspp2.ConsultarFacturaResponse consultarFactura(string numeroRegistro)
        {
            return base.Channel.consultarFactura(numeroRegistro);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarFacturaResponse> consultarFacturaAsync(string numeroRegistro)
        {
            return base.Channel.consultarFacturaAsync(numeroRegistro);
        }

        public servicioFaceWCF.facturasspp2.AnularFacturaResponse anularFactura(string numeroRegistro, string motivo)
        {
            return base.Channel.anularFactura(numeroRegistro, motivo);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.AnularFacturaResponse> anularFacturaAsync(string numeroRegistro, string motivo)
        {
            return base.Channel.anularFacturaAsync(numeroRegistro, motivo);
        }

        public servicioFaceWCF.facturasspp2.ConsultarEstadosResponse consultarEstados()
        {
            return base.Channel.consultarEstados();
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarEstadosResponse> consultarEstadosAsync()
        {
            return base.Channel.consultarEstadosAsync();
        }

        public servicioFaceWCF.facturasspp2.ConsultarRelacionesResponse consultarUnidades()
        {
            return base.Channel.consultarUnidades();
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarRelacionesResponse> consultarUnidadesAsync()
        {
            return base.Channel.consultarUnidadesAsync();
        }

        public servicioFaceWCF.facturasspp2.ConsultarNIFsResponse consultarNIFs()
        {
            return base.Channel.consultarNIFs();
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarNIFsResponse> consultarNIFsAsync()
        {
            return base.Channel.consultarNIFsAsync();
        }

        public servicioFaceWCF.facturasspp2.ConsultarAdministracionesResponse consultarAdministraciones()
        {
            return base.Channel.consultarAdministraciones();
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarAdministracionesResponse> consultarAdministracionesAsync()
        {
            return base.Channel.consultarAdministracionesAsync();
        }

        public servicioFaceWCF.facturasspp2.ConsultarAdministracionesRepositorioResponse consultarAdministracionesRepositorio()
        {
            return base.Channel.consultarAdministracionesRepositorio();
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarAdministracionesRepositorioResponse> consultarAdministracionesRepositorioAsync()
        {
            return base.Channel.consultarAdministracionesRepositorioAsync();
        }

        public servicioFaceWCF.facturasspp2.ConsultarRelacionesPorAdministracionResponse consultarUnidadesPorAdministracion(string codigoDir)
        {
            return base.Channel.consultarUnidadesPorAdministracion(codigoDir);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarRelacionesPorAdministracionResponse> consultarUnidadesPorAdministracionAsync(string codigoDir)
        {
            return base.Channel.consultarUnidadesPorAdministracionAsync(codigoDir);
        }

        public servicioFaceWCF.facturasspp2.ConsultarNIFsPorAdministracionResponse consultarNIFsPorAdministracion(string codigoDir)
        {
            return base.Channel.consultarNIFsPorAdministracion(codigoDir);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.ConsultarNIFsPorAdministracionResponse> consultarNIFsPorAdministracionAsync(string codigoDir)
        {
            return base.Channel.consultarNIFsPorAdministracionAsync(codigoDir);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort.consultarListadoFacturas(servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest request)
        {
            return base.Channel.consultarListadoFacturas(request);
        }

        public servicioFaceWCF.facturasspp2.ConsultarListadoFacturaResponse consultarListadoFacturas(string[] request)
        {
            servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest inValue = new servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest();
            inValue.request = request;
            servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse retVal = ((servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort)(this)).consultarListadoFacturas(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse> servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort.consultarListadoFacturasAsync(servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest request)
        {
            return base.Channel.consultarListadoFacturasAsync(request);
        }

        public System.Threading.Tasks.Task<servicioFaceWCF.facturasspp2.consultarListadoFacturasResponse> consultarListadoFacturasAsync(string[] request)
        {
            servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest inValue = new servicioFaceWCF.facturasspp2.consultarListadoFacturasRequest();
            inValue.request = request;
            return ((servicioFaceWCF.facturasspp2.FacturaSSPPWebServiceProxyPort)(this)).consultarListadoFacturasAsync(inValue);
        }
    }
}
